name: Check sanity of benchmark results file
on:
  pull_request:


jobs:
  benchmarks_file_sanity_checks:
    name: Run check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pre-requisites
      run: pip install numpy pandas

    - name: Check sanity of benchmark files
      run: |
        python ./benchmarks/kmeans/consolidate_result_csv.py ./benchmarks/kmeans/results.csv --check-csv
        python ./benchmarks/pca/consolidate_result_csv.py ./benchmarks/pca/results.csv --check-csv
